name: app

type: php:8.4

runtime:
    extensions:
        - apcu
        - mbstring
        - mongodb
        - sodium
        - ctype
        - iconv
    env:
        variables:
            MONGODB_URL: 'mongodb://${env:PLATFORM_RELATIONSHIPS.mongodb[0].host}:${env:PLATFORM_RELATIONSHIPS.mongodb[0].port}/your_database_name'    

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }

relationships:
    database: 'database:mysql'
    service: mongodb-enterprise
        endpoint: mongodb
    

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e

        symfony-deploy
