
    name: app

    services:
        database:
            type: mysql:10.6
            disk: 512
        mongodb:
            type: mongodb:4.4   # Utiliser mongodb plutôt que mongodb-enterprise
            disk: 512
